services:
  app:
    build:
      context: .
      dockerfile: ./.docker/golang/Dockerfile
    ports: 
      - "80:3000/tcp"
    volumes:
      - type: bind
        source: .
        target: /var/www/html
    networks: 
      - webproxy2

networks:
  webproxy2:
    driver: bridge